version: "2"
services:
  jenkins_master:
    container_name: jenkins_master
    image: jenkinsci/jenkins
    restart: always
    ports:
    - "8080:8080"
    - "50000:50000"
    volumes:
    - /data/jenkins:/var/jenkins_home

  jenkins_slave_1:
    container_name: jenkins_slave_1
    image: jaydp17/jenkins-slave
    depends_on:
      - jenkins_master
    links:
      - jenkins_master
    volumes:
    - /data/jenkins:/var/jenkins_home
